version: '3.8'

services:
  rexus-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rexus-dev
    volumes:
      # Montar código fuente para hot-reload
      - .:/app
      # Preservar node_modules y cache de Python
      - python_cache:/root/.cache/pip
    ports:
      # Puerto para VNC (debugging visual opcional)
      - "5900:5900"
      # Puerto para web server si se necesita
      - "8000:8000"
    environment:
      - DISPLAY=:99
      - QT_QPA_PLATFORM=xcb
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - rexus-network

  # Base de datos SQL Server (opcional, para desarrollo completo)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: rexus-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DevPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - rexus-network

volumes:
  python_cache:
  sqlserver_data:

networks:
  rexus-network:
    driver: bridge
