name: 游늵 Calidad de C칩digo

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Lunes a las 2 AM

jobs:
  quality:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: 游냀 Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: 游닍 Instalar herramientas
      run: |
        pip install flake8 black isort mypy
        pip install -r requirements.txt

    - name: 游꿛 Verificar formato de c칩digo
      run: |
        black --check modules/ core/ utils/ scripts/
        isort --check-only modules/ core/ utils/ scripts/

    - name: 游댌 An치lisis est치tico
      run: |
        flake8 modules/ core/ utils/ --max-line-length=88
        mypy modules/ core/ utils/ --ignore-missing-imports

    - name: 游늳 Ejecutar an치lisis autom치tico
      run: |
        python scripts/verificacion/analizador_modulos.py
        python scripts/verificacion/metricas_rapidas.py

    - name: 游닋 Guardar reportes
      uses: actions/upload-artifact@v3
      with:
        name: quality-reports
        path: |
          METRICAS_RAPIDAS_*.md
          informes_modulos/
